# Generated by Django 5.1.4 on 2024-12-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendive', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(related_name='attendees', to='event.event'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
